### ISSUE TITLE
too many false positives

### ISSUE THREAD

**Issue by siggijarl** [amoscardino/video-check#1]
the ffmpeg command used seems to output the following errors for some files:

```
[null @ 000002e2768dd8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 82 >= 82
[null @ 000002e2768dd8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 381 >= 381
[null @ 000002e2768dd8c0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 680 >= 680
```

when the file is working perfectly fine in Plex and other players with no problems.

**Comment by amoscardino** [comment]
I get what you’re saying, but I’m not sure it is something that can be fixed. Plex uses a custom build of ffmpeg which makes this tool imprecise by default. Not all errors it finds will result in an unplayable video in Plex, and conversely a video may pass this tool and fail to play in Plex. This isn’t meant to be a perfect catch-all, but a quick check for common errors.
